export default {
  BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
  AJAX_CALL_ERROR: 'AJAX_CALL_ERROR',
  SIGN_IN: 'SIGN_IN',
  SIGIN_IN_FAILED: 'SIGIN_IN_FAILED',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_IN_FORM_RESET: 'SIGN_IN_FORM_RESET',
  CHANGE_CREDENTIAL: 'CHANGE_CREDENTIAL',
  LOAD_VIDEOS_SUCCESS: 'LOAD_VIDEOS_SUCCESS',
  LOAD_VIDEOS_ERROR: 'LOAD_VIDEOS_ERROR',
  RATING_SUCCESS: 'RATING_SUCCESS',
  RATING_ERROR: 'RATING_ERROR',
  VIDEO_SUCCESS: 'VIDEO_SUCCESS',
  VIDEO_ERROR: 'VIDEO_ERROR',
  CLEAR_VIDEOS: 'CLEAR_VIDEOS'
};

